settings:
  title: '服务器状态'
  url: 'http://status.esnnn.com' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 30 # number of days you want to display in histogram
  collectResponseTimes: false # collects avg response times from CRON locations

  allmonitorsOperational: '已检查所有服务器'
  notAllmonitorsOperational: '已检查部分服务器'
  monitorLabelOperational: '已检查'
  monitorLabelNotOperational: '未检查'
  monitorLabelNoData: '没有数据'
  dayInHistogramNoData: '没有数据'
  dayInHistogramOperational: '检查正常'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: df1 # unique identifier
    name: API服务
    description: '用于提供API服务' # default=empty
    url: 'http://api3.esnnn.com/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: false # allows the title to be a link, default=true
  - id: cmy
    name: CMY服务器
    description: '控制端服务器，包含一些基础服务.'
    url: 'http://cmy.esnnn.com/'
    method: GET
    expectStatus: 200
    linkable: false 
  - id: df4
    name: df4独立服务器
    description: 'df4独立服务器.'
    url: 'http://142.54.189.18:8007'
    method: GET
    expectStatus: 200
    linkable: false 
  - id: df5
    name: df5独立服务器
    description: 'df5独立服务器.'
    url: 'http://142.54.189.186:8007/'
    method: GET
    expectStatus: 200
    linkable: false 
  - id: phone
    name: 新机服务器
    description: '提供新机服务.'
    url: 'http://fh.esnnn.com/'
    method: GET
    expectStatus: 200
    linkable: false 
  - id: TXs3XD
    name: 腾讯S3成都
    description: '腾讯S3成都.'
    url: 'http://1.14.60.131:8700/'
    method: GET
    expectStatus: 404
    linkable: false 
  - id: ProductServer
    name: S0移动主服务器
    description: 'S0移动主服务器.'
    url: 'http://112.18.10.71:8007/'
    method: GET
    expectStatus: 200
    linkable: false 
  - id: hs100
    name: hs100备用服务器
    description: 'hs100备用服务器.'
    url: 'https://hs100.zoogooo.com'
    method: GET
    expectStatus: 404
    linkable: false 
  
    
